#!/usr/bin/env python3
"""Reference fixtures for core_beam_decode's HF semantics (tests/test-beam-hf.cpp).

Runs REAL transformers `generate(num_beams=...)` on a toy decoder whose next-token
logits are a fixed random table row picked by an integer hash of the whole
sequence - so the C++ test can reproduce every logit bit for bit and compare
token sequences exactly. Swept: beam width, length_penalty, early_stopping
(False / True / "never"), max_new_tokens, min_new_tokens, one or two EOS ids,
repetition_penalty (a processor that runs after log_softmax in beam search).

    PYTHONPATH=<transformers 4.57.3> python tools/gen_beam_hf_fixtures.py > tests/fixtures/beam_hf_cases.h
"""
import itertools, random, sys

import numpy as np
import torch
from torch import nn
import transformers
from transformers import GenerationMixin, PretrainedConfig, PreTrainedModel
from transformers.modeling_outputs import CausalLMOutputWithPast

V, R = 16, 997


def seq_hash(ids):
    h = 1469598103
    for t in ids:
        h = (h * 1000003 + int(t) + 7) % 2147483648
    return h


rng = np.random.default_rng(1234)
TABLE = (rng.standard_normal((R, V)) * 2.0).astype(np.float32)


class ToyConfig(PretrainedConfig):
    model_type = "crispasr_toy"

    def __init__(self, **kw):
        super().__init__(**kw)
        self.vocab_size = V


class Toy(PreTrainedModel, GenerationMixin):
    config_class = ToyConfig

    def __init__(self, cfg):
        super().__init__(cfg)
        self.dummy = nn.Parameter(torch.zeros(1))
        self.table = torch.from_numpy(TABLE)

    def forward(self, input_ids=None, attention_mask=None, **kw):
        Bn, L = input_ids.shape
        out = torch.zeros(Bn, L, V)
        for b in range(Bn):
            out[b, -1] = self.table[seq_hash(input_ids[b].tolist()) % R]
        return CausalLMOutputWithPast(logits=out)

    def prepare_inputs_for_generation(self, input_ids, **kw):
        return {"input_ids": input_ids}


model = Toy(ToyConfig(pad_token_id=15, bos_token_id=14)).eval()
cases = []
random.seed(7)
grid = list(itertools.product([1, 2, 3, 4, 5], [1.0, 0.0, 2.0, -0.5], [False, True, "never"], [3, 8, 20]))
for i, (nb, lp, es, mx) in enumerate(grid):
    prompt = [random.randrange(2, 14) for _ in range(random.randint(1, 4))]
    eos = [0] if i % 3 else [0, 1]
    min_new = 2 if i % 5 == 0 else 0
    rep = 1.5 if i % 4 == 0 else 1.0
    with torch.no_grad():
        out = model.generate(torch.tensor([prompt]), num_beams=nb, length_penalty=lp, early_stopping=es,
                             max_new_tokens=mx, min_new_tokens=min_new or None, eos_token_id=eos,
                             repetition_penalty=rep, do_sample=False, use_cache=False, pad_token_id=15)
    gen = out[0, len(prompt):].tolist()
    # trailing pad (never generated by the search itself) would come from batch padding: batch is 1, so none
    cases.append((prompt, nb, lp, {False: 0, True: 1, "never": 2}[es], mx, min_new, eos, rep, gen, -1))
# forced BOS (m2m100's target-language token): transformers GENERATES it at step 1,
# the C++ callers put it in the prompt and pass length_offset = 1
for i, (nb, lp, es, mx) in enumerate(itertools.product([2, 4, 5], [1.0, 2.0], [False, True], [4, 12])):
    prompt, forced = [random.randrange(2, 14)], random.randrange(2, 14)
    with torch.no_grad():
        out = model.generate(torch.tensor([prompt]), num_beams=nb, length_penalty=lp, early_stopping=es,
                             max_new_tokens=mx + 1, eos_token_id=[0], forced_bos_token_id=forced, do_sample=False,
                             use_cache=False, pad_token_id=15)
    gen = out[0, len(prompt):].tolist()
    assert gen[0] == forced
    cases.append((prompt + [forced], nb, lp, {False: 0, True: 1}[es], mx, 0, [0], 1.0, gen[1:], forced))

w = sys.stdout.write
w("// Generated by tools/gen_beam_hf_fixtures.py with transformers %s - do not edit.\n" % transformers.__version__)
w("#pragma once\n#include <vector>\nnamespace beam_hf_fixture {\n")
w("constexpr int V = %d, R = %d;\n" % (V, R))
w("static const float TABLE[R][V] = {\n")
for row in TABLE:
    w("{" + ",".join("%.9gf" % x for x in row) + "},\n")
w("};\nstruct Case { std::vector<int> prompt; int beams; float lp; int early; int max_new; int min_new;"
  " std::vector<int> eos; float rep; std::vector<int> expect; int forced; };\n")
w("static const std::vector<Case> CASES = {\n")
for p, nb, lp, es, mx, mn, eos, rep, gen, fb in cases:
    L = lambda v: "{" + ",".join(map(str, v)) + "}"
    w("{%s,%d,%.3ff,%d,%d,%d,%s,%.3ff,%s,%d},\n" % (L(p), nb, lp, es, mx, mn, L(eos), rep, L(gen), fb))
w("};\n} // namespace beam_hf_fixture\n")
print(f"{len(cases)} cases", file=sys.stderr)
